# docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - websocket-service

  websocket-service:
    build:
      context: .
    container_name: websocket-service
    command: node websocket.js
    ports:
      - "8080:8080"
